name: Build Kernel S25
on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build Kernel S25 by ${{ github.actor }}
    runs-on: ubuntu-24.04
    steps:

      - name: Set Beijing timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: Set SWAP to 5GiB
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: Clean useless files
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Initialize compilation environment
        run: |
          sudo apt-get update
          sudo apt-get install git automake build-essential bc python-is-python3 gcc-aarch64-linux-gnu -y
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
          
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Toolchain
        run: |
          git clone https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b.git --depth 1 toolchain/clang
          git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9.git --depth=1 toolchain/gcc32
          git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9.git --depth=1 toolchain/gcc64
          git clone https://github.com/KopsourcesORG/python-2.7.18-prebuilt.git --depth=1 toolchain/python2

      - name: Build Kernel
        run: |
          export KBUILD_BUILD_HOST=Github-Action
          export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
          export ARCH="arm64"
          export SUBARCH="arm64"
          export PATH="$GITHUB_WORKSPACE/toolchain/clang/bin:$GITHUB_WORKSPACE/toolchain/gcc32/bin:$GITHUB_WORKSPACE/toolchain/gcc64/bin:$GITHUB_WORKSPACE/toolchain/python2/bin:$PATH"
          export CC="clang"
          export CROSS_COMPILE="aarch64-linux-android-"
          export CROSS_COMPILE_ARM32="arm-linux-androideabi-"
          export TRIPLE="aarch64-linux-android-"
          make O=out s25_defconfig
          make -j$(nproc --all) O=out
          
      - name: Upload Kernel Package
        uses: actions/upload-artifact@v4
        with:
          name: Kernel_S25_${{ env.BUILD_TIME }}
          path: out/arch/arm64/boot/*
          